[versions]
micronaut-platform-version = "4.9.0"
kotlin-version = "2.2.0"
devtools-ksp-version = "2.2.0-2.0.2"
micronaut-application-version = "4.6.1"
frontend-jdk21-version = "10.0.0"

[libraries]
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-version" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-version" }
micronautPlatform = { group = "io.micronaut.platform", name = "micronaut-parent", version.ref = "micronaut-platform-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp-version" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-application-version" }
frontend-jdk21 = {id="org.siouan.frontend-jdk21", version.ref="frontend-jdk21-version"}